kind = "DojoModel"
class_hash = "0x4be10cbeb28a10a5b5e5fb55c41269de0fb6ea6eaeec2ac11395e186b9f9e1c"
original_class_hash = "0x4be10cbeb28a10a5b5e5fb55c41269de0fb6ea6eaeec2ac11395e186b9f9e1c"
abi = "manifests/sepolia/abis/base/models/zkastle_models_index_player.json"
name = "zkastle::models::index::player"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "game_id"
type = "u32"
key = false

[[members]]
name = "card_id"
type = "u8"
key = false

[[members]]
name = "achievements"
type = "u32"
key = false

[[members]]
name = "enables"
type = "u32"
key = false

[[members]]
name = "name"
type = "felt252"
key = false
