kind = "DojoModel"
class_hash = "0x6308886f3055519e49edb15fcf180601b3d11fef4e8d1ad54eb25b54b39b684"
original_class_hash = "0x6308886f3055519e49edb15fcf180601b3d11fef4e8d1ad54eb25b54b39b684"
abi = "manifests/dev/abis/base/models/zkastle_models_index_game.json"
name = "zkastle::models::index::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "card_one"
type = "u8"
key = false

[[members]]
name = "card_two"
type = "u8"
key = false

[[members]]
name = "card_three"
type = "u8"
key = false

[[members]]
name = "deck"
type = "u8"
key = false

[[members]]
name = "move_count"
type = "u8"
key = false

[[members]]
name = "pointer"
type = "u8"
key = false

[[members]]
name = "store_count"
type = "u8"
key = false

[[members]]
name = "stores"
type = "u16"
key = false

[[members]]
name = "cards"
type = "u64"
key = false

[[members]]
name = "sides"
type = "u64"
key = false

[[members]]
name = "indexes"
type = "u64"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false
