kind = "DojoModel"
class_hash = "0x51d7aade4568c82305c03389db2499d12da087903e0699d03b484cec9a73dc9"
original_class_hash = "0x51d7aade4568c82305c03389db2499d12da087903e0699d03b484cec9a73dc9"
abi = "manifests/dev/abis/base/models/zkastle_models_index_player.json"
name = "zkastle::models::index::player"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "game_id"
type = "u32"
key = false

[[members]]
name = "achievements"
type = "u64"
key = false

[[members]]
name = "name"
type = "felt252"
key = false
