kind = "DojoModel"
class_hash = "0x3b83b21ab47663de8cbc824d9d66f075092f534d61502acd98f967364b75661"
original_class_hash = "0x3b83b21ab47663de8cbc824d9d66f075092f534d61502acd98f967364b75661"
abi = "manifests/dev/abis/base/models/zkastle_models_index_game.json"
name = "zkastle::models::index::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "card_one"
type = "u8"
key = false

[[members]]
name = "card_two"
type = "u8"
key = false

[[members]]
name = "card_three"
type = "u8"
key = false

[[members]]
name = "deck"
type = "u8"
key = false

[[members]]
name = "move_count"
type = "u8"
key = false

[[members]]
name = "stores"
type = "u32"
key = false

[[members]]
name = "sides"
type = "u64"
key = false

[[members]]
name = "cards"
type = "u128"
key = false

[[members]]
name = "player_id"
type = "felt252"
key = false
