kind = "DojoModel"
class_hash = "0x4c8f7ba6e969f568fc32b44915c2fa890ebce91ecc12a77452c772d39d51546"
original_class_hash = "0x4c8f7ba6e969f568fc32b44915c2fa890ebce91ecc12a77452c772d39d51546"
abi = "manifests/dev/abis/base/models/zkastle_models_index_game.json"
name = "zkastle::models::index::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "card_one"
type = "u8"
key = false

[[members]]
name = "card_two"
type = "u8"
key = false

[[members]]
name = "card_three"
type = "u8"
key = false

[[members]]
name = "deck"
type = "u8"
key = false

[[members]]
name = "move_count"
type = "u8"
key = false

[[members]]
name = "pointer"
type = "u8"
key = false

[[members]]
name = "store_count"
type = "u8"
key = false

[[members]]
name = "stores"
type = "u16"
key = false

[[members]]
name = "cards"
type = "u64"
key = false

[[members]]
name = "sides"
type = "u64"
key = false

[[members]]
name = "indexes"
type = "u64"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false
