[package]
name = "zkastle"
version = "0.0.0"
edition = "2023_10"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo --profile dev clean && sozo --profile dev build && sozo --profile dev migrate plan && sozo --profile dev migrate apply"
slot = "NAME=v1 && sozo --profile slot clean && sozo --profile slot build && sozo --profile slot migrate plan --name $NAME && sozo --profile slot migrate apply --name $NAME"
sepolia = "NAME=v1 && sozo --profile sepolia clean && sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia migrate plan --name $NAME && sozo --profile sepolia migrate apply --fee-estimate-multiplier 10 --name $NAME"

[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "78b0d51" }
origami = { git = "https://github.com/dojoengine/origami", tag = "v0.7.2" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.2" }
stark_vrf = { git = "https://github.com/Bal7hazar/stark-vrf", rev = "07fa95f" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[profile.dev.tool.dojo.env]
rpc_url = "http://localhost:5050/"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"

[profile.slot.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/zkastle/katana"
account_address = "0x7f72521e15721c6e0ea834aee0ca964147b6de30351ba761b3548f7d1a8beb8"
private_key = "0x31f6f3f619373d03d9a7dcf219f863925f470ee577577f7731d510ce81cbed6"

# Sepolia
[profile.sepolia.tool.dojo.env]
rpc_url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_7"
#rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_6"
#rpc_url = "https://free-rpc.nethermind.io/sepolia-juno/v0_6"
#rpc_url = "https://rpc.nethermind.io/sepolia-juno/v0_6?apiKey=supVUiu9olj34NdcUsq6T5dAFsp0ZpjMHyWlGJ1Zd6GtRiVr"
account_address = ""
private_key = ""

[tool.dojo.world]
name = "zKastle"
description = "Solo strategy card game where you manage resources and upgrade your village to maximize points. Make tactical decisions to help your village grow and flourish."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://app.zkastle.xyz"

[tool.dojo.world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"
