kind = "DojoContract"
class_hash = "0x531d88a9a1637f61e7842d5e291b90b714d26ad215b853d945434c2ef871552"
original_class_hash = "0x531d88a9a1637f61e7842d5e291b90b714d26ad215b853d945434c2ef871552"
base_class_hash = "0x0"
abi = "manifests/slot/abis/base/contracts/zkastle_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkastle::systems::actions::actions"
