kind = "DojoContract"
class_hash = "0x5f2f286a6c36bc04e3317d9a622a87063d6a8e90876a44dcc50477f057becb5"
original_class_hash = "0x5f2f286a6c36bc04e3317d9a622a87063d6a8e90876a44dcc50477f057becb5"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkastle_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkastle::systems::actions::actions"
