kind = "DojoContract"
class_hash = "0x637413abf87e5fc283bb40b9da819c9e3177d64562646697521603b97acefe9"
original_class_hash = "0x637413abf87e5fc283bb40b9da819c9e3177d64562646697521603b97acefe9"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkastle_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkastle::systems::actions::actions"
