kind = "DojoContract"
class_hash = "0x646b07c04db6354ae415873aa89e4afbadd1dec8211707542a19c43e885df88"
original_class_hash = "0x646b07c04db6354ae415873aa89e4afbadd1dec8211707542a19c43e885df88"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkastle_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkastle::systems::actions::actions"
