kind = "DojoContract"
class_hash = "0x4cec7e554fbb811f3be805d2fe768fd11fb9c3cc6da93602e47efe04674a885"
original_class_hash = "0x4cec7e554fbb811f3be805d2fe768fd11fb9c3cc6da93602e47efe04674a885"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkastle_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkastle::systems::actions::actions"
