kind = "DojoContract"
class_hash = "0x716b92aad55e06cae88b00225fc2bc411a3c052acc774de4fba6bf32c9af0b0"
original_class_hash = "0x716b92aad55e06cae88b00225fc2bc411a3c052acc774de4fba6bf32c9af0b0"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkastle_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkastle::systems::actions::actions"
