kind = "DojoContract"
class_hash = "0x42054984ed97e284c4a97e698f2771f8b863ebc4d0d7b7c371d78d49c487447"
original_class_hash = "0x42054984ed97e284c4a97e698f2771f8b863ebc4d0d7b7c371d78d49c487447"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkastle_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkastle::systems::actions::actions"
