kind = "DojoContract"
class_hash = "0x6657e50ff18d9f1347b99173c472958400cfef9651b77b86af14a2c99a19c0a"
original_class_hash = "0x6657e50ff18d9f1347b99173c472958400cfef9651b77b86af14a2c99a19c0a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkastle_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkastle::systems::actions::actions"
