kind = "DojoContract"
class_hash = "0x7fa4a9280be6c689dd7d6bf5130eb44dcc39ae5c849fa27805c1db3e78e4646"
original_class_hash = "0x7fa4a9280be6c689dd7d6bf5130eb44dcc39ae5c849fa27805c1db3e78e4646"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkastle_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkastle::systems::actions::actions"
