kind = "DojoContract"
class_hash = "0x374fe4828d299669e43f5c0df628830617a61006316e2ddb4264d3b63a42e15"
original_class_hash = "0x374fe4828d299669e43f5c0df628830617a61006316e2ddb4264d3b63a42e15"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkastle_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkastle::systems::actions::actions"
